name: neuromodulation-models
channels:
  - pytorch
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - defaults
dependencies:
  - accelerate=1.4.0
  - aom=3.6.1
  - appnope=0.1.2
  - apricot-select=0.6.1
  - arviz=0.17.1
  - asttokens=2.0.5
  - atk-1.0=2.38.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - backcall=0.2.0
  - blas=1.0
  - bokeh=3.4.3
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cairo=1.18.0
  - cctools_osx-arm64=986
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - clang=16.0.6
  - clang-16=16.0.6
  - clang_impl_osx-arm64=16.0.6
  - clang_osx-arm64=16.0.6
  - clangxx=16.0.6
  - clangxx_impl_osx-arm64=16.0.6
  - clangxx_osx-arm64=16.0.6
  - click=8.1.8
  - cloudpickle=3.1.1
  - cmdstan=2.35.0
  - cmdstanpy=1.2.5
  - colorama=0.4.6
  - comm=0.2.1
  - compiler-rt=16.0.6
  - compiler-rt_osx-arm64=16.0.6
  - cons=0.4.6
  - contourpy=1.2.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.27
  - cytoolz=1.0.1
  - dask=2024.8.0
  - dask-core=2024.8.0
  - dask-expr=1.1.10
  - dav1d=1.2.1
  - decorator=5.1.1
  - distributed=2024.8.0
  - eigen=3.4.0
  - etuples=0.3.9
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.6.4
  - fastprogress=1.0.3
  - ffmpeg=6.1.1
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2025.2.0
  - gdk-pixbuf=2.42.10
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - graphviz=4.0.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gtk2=2.24.33
  - gts=0.7.6
  - h2=4.2.0
  - h5netcdf=1.5.0
  - h5py=3.12.1
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - holidays=0.68
  - hpack=4.1.0
  - huggingface_hub=0.29.1
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - imagecodecs-lite=2019.12.3
  - imageio=2.37.0
  - importlib-metadata=8.6.1
  - importlib_metadata=8.6.1
  - importlib_resources=6.4.0
  - ipython=8.15.0
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - ld64_osx-arm64=711
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.7
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang-cpp16=16.0.6
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcurl=8.12.1
  - libcxx=19.1.7
  - libcxx-devel=16.0.6
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgd=2.3.3
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.80.2
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.23.1
  - libintl-devel=0.23.1
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm16=16.0.6
  - libltdl=2.4.3a
  - libnghttp2=1.58.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libparquet=16.1.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librsvg=2.56.3
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libtheora=1.1.1
  - libthrift=0.19.0
  - libtiff=4.5.1
  - libtool=2.5.4
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - llvm-tools=16.0.6
  - llvmlite=0.43.0
  - locket=1.0.0
  - logical-unification=0.4.6
  - lz4=4.3.3
  - lz4-c=1.9.4
  - macosx_deployment_target_osx-arm64=11.0
  - make=4.4.1
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - minikanren=1.0.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multipledispatch=0.6.0
  - mysql=8.4.0
  - ncurses=6.5
  - networkx=3.2.1
  - nose=1.3.7
  - numba=0.60.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.5
  - openssl=3.4.1
  - orc=2.0.1
  - packaging=24.2
  - pacmap=0.8.0
  - pandas=2.2.3
  - pango=1.50.7
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.44.2
  - plotly=5.24.1
  - pomegranate=1.0.0
  - prompt-toolkit=3.0.43
  - prophet=1.1.5
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pybind11-abi=4
  - pycparser=2.22
  - pygments=2.15.1
  - pymc=5.12.0
  - pymc-base=5.12.0
  - pynndescent=0.5.13
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - pytensor=2.19.0
  - pytensor-base=2.19.0
  - python=3.9.18
  - python-annoy=1.17.3
  - python-dateutil=2.9.0post0
  - python-graphviz=0.20.3
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=2.5.1
  - pytz=2024.1
  - pywavelets=1.6.0
  - pyyaml=6.0.2
  - qt-main=5.15.2
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.3
  - safetensors=0.5.3
  - scikit-image=0.20.0
  - scikit-learn=1.6.1
  - scipy=1.9.1
  - seaborn=0.13.2
  - setuptools=72.1.0
  - sigtool=0.1.3
  - six=1.16.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - stanio=0.5.1
  - statsmodels=0.14.4
  - stumpy=1.13.0
  - sympy=1.13.3
  - tapi=1100.0.11
  - tbb=2021.13.0
  - tbb-devel=2021.13.0
  - tblib=3.0.0
  - tenacity=9.0.0
  - tesseract=5.2.0
  - threadpoolctl=3.5.0
  - tifffile=2020.6.3
  - tk=8.6.14
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - tsfresh=0.21.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - umap-learn=0.5.7
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wcwidth=0.2.5
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xarray=2024.3.0
  - xarray-einstats=0.7.0
  - xyzservices=2025.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
